ARCH=arm
CROSS_ROOT := toolchain/uclibc/bin
CROSS_TRIPLET=arm-buildroot-linux-uclibcgnueabi
CROSS=${CROSS_ROOT}/${CROSS_TRIPLET}-
XTRA_LDFLAGS :=

CC=${CROSS}gcc
USERCC=${CROSS}gcc
AR=${CROSS}ar
RANLIB=${CROSS}ranlib
CC_AR=${AR} -r ${LIBAR}
PARTIALLD=${CROSS}ld -r --whole-archive

ONELIB=0
OSTYPE=gnulinux
PICFLAGS=-fPIC -fpic
CFLAGS+=${PICFLAGS}
LDFLAGS+=-ldl -pthread -lutil $(XTRA_LDFLAGS)
CC_LIB=${CC} -shared -o
CFLAGS_INCLUDE=-I
LDFLAGS_LINK=-l
LDFLAGS_LINKPATH=-L
CFLAGS_OPT0=-O0
CFLAGS_OPT1=-O1
CFLAGS_OPT2=-O2
CFLAGS_OPT3=-O3
CFLAGS_DEBUG=-g
