#!/bin/sh

# Set search library path and user path
LD_LIBRARY_PATH=/tmp/sd/OVERLAY/mnt/lib:/tmp/sd/OVERLAY/mnt/usr/lib:/lib:/usr/lib
PATH=/tmp/sd/OVERLAY/mnt/bin:/tmp/sd/OVERLAY/mnt/sbin:/tmp/sd/OVERLAY/mnt/usr/bin:/tmp/sd/OVERLAY/mnt/usr/sbin:/bin:/sbin:/usr/bin:/usr/sbin
export LD_LIBRARY_PATH PATH

#host name
USER="`id -un`"
LOGNAME=$USER
HOSTNAME='/bin/hostname'
export USER LOGNAME HOSTNAME

#alias
alias ll="ls -al"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Get anyka_ipc checksum
export anyka_md5=`md5sum /usr/bin/anyka_ipc | grep "anyka_ipc" | awk '{print \$1}'`

# Get device mac
export device_mac=`ifconfig wlan0 | grep HWaddr | awk '{print $5}'`

# Set device uid
export device_uid=`echo $device_mac | sha256sum | cut -d " " -f1`

# prompt Set PS1
export PS1='[\u@\h \w]$ '
echo -e "  _       _____  _____                       __ _           _\n | |     / ___/ / ____|                     / _| |         | |\n | |    | (___ | |     __ _ _ __ ___   ___ | |_| | __ _ ___| |__\n | |     \\___ \\| |    / _\` | '_ \` _ \\ / _ \\|  _| |/ _\` / __| '_ \\ \n | |____ ____) | |___| (_| | | | | | | (_) | | | | (_| \\__ \\ | | |\n |______|_____/ \\_____\\__,_|_| |_| |_|\\___/|_| |_|\\__,_|___/_| |_|\n\n  https://github.com/Bunkerschild/LSCamoflash\n"
defaultpw='$1$YjgTo5mH$ADPfZ0ejO6cxknnlP3F/K.'
shadowpw=`cat /etc/config/shadow | grep "^root" | cut -d : -f2`
if [ "$defaultpw" = "$shadowpw" ]; then
  echo "  IMPORTANT:"
  echo "  DEFAULT PASSWORD IS SET"
  echo "  To change default password for telnet, ftp and httpd type: chpasswd"
  echo "  Do not use 'passwd' as it does not survive a reboot"
fi
echo "/tmp/core_%e_%p_%t" > /proc/sys/kernel/core_pattern
