#!/bin/sh

# Set search library path and user path
LD_LIBRARY_PATH=/tmp/sd/OVERLAY/mnt/lib:/tmp/sd/OVERLAY/mnt/usr/lib:/lib:/usr/lib
PATH=/tmp/sd/OVERLAY/mnt/bin:/tmp/sd/OVERLAY/mnt/sbin:/tmp/sd/OVERLAY/mnt/usr/bin:/tmp/sd/OVERLAY/mnt/usr/sbin:/bin:/sbin:/usr/bin:/usr/sbin
export LD_LIBRARY_PATH PATH

#host name
USER="`id -un`"
LOGNAME=$USER
HOSTNAME='/bin/hostname'
export USER LOGNAME HOSTNAME

#alias
alias ll="ls -al"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Get anyka_ipc checksum
export anyka_md5=`md5sum /usr/bin/anyka_ipc | grep "anyka_ipc" | awk '{print \$1}'`

# Get device mac
export device_mac=`ifconfig wlan0 | grep HWaddr | awk '{print $5}'`

# Set device uid
export device_uid=`echo $device_mac | sha256sum | cut -d " " -f1`

# prompt Set PS1
export PS1='[\u@\h \w]$ '
echo "This device is running LSCamoflash by Bunkerschild"
echo "/tmp/core_%e_%p_%t" > /proc/sys/kernel/core_pattern
