name: Auto-Build & Deploy

on:
  push:
    branches:
      - main  # Läuft nur, wenn auf "main" gepusht wird
  pull_request:
    branches:
      - main  # Optional: PRs prüfen

jobs:
  build:
    runs-on: ubuntu-latest  # Läuft auf einem Ubuntu-Runner

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Installiere Build-Tools
        run: sudo apt update && sudo apt install -y build-essential flex bison gsoap binutils make automake autoconf

      - name: Starte Build
        run: |
          cd SOURCE
          make download toolchain packages staging
