name: Build-Test

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'SOURCE/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Installiere Build-Tools
        run: sudo apt update && sudo apt install -y build-essential flex bison gsoap binutils make automake autoconf autoconf-archive

      - name: Download der Quellen
        run: |
          cd SOURCE
          make mrproper-full download

      - name: Starte Build-Test mit uclibc
        run: |
          cd SOURCE
          make build-test-uclibc

      - name: Starte Build-Test mit gclibc
        run: |
          cd SOURCE
          make build-test-glibc
