name: Auto-Build & Deploy
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches:
      - main  # Läuft nur, wenn auf "main" gepusht wird
  pull_request:
    branches:
      - main  # Optional: PRs prüfen

jobs:
  build:
    runs-on: ubuntu-latest  # Läuft auf einem Ubuntu-Runner

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Installiere Build-Tools
        run: sudo apt update && sudo apt install -y build-essential flex bison gsoap binutils make automake autoconf autoconf-archive

      - name: Download der Quellen
        run: |
          cd SOURCE
          make mrproper-full download
          
      - name: Starte Build-Test mit uclibc
        run: |
          cd SOURCE
          make build-test-uclibc
          
      - name: Release erstellen
        run: |
          cd SOURCE
          make release
          mkdir -p ../docs/autobuild
          cp build/LSCamoflash-*-uclibc.tar.gz ../doc/autobuild/LSCamoflash-Autobuild.tar.gz

      - name: Update erstellen
        run: |
          cd SOURCE
          make update
          mkdir -p ../docs/autobuild
          cp build/update-*-uclibc.tgz ../docs/autobuild/update-autobuild.tgz

      - name: Build als Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: LSCamoflash-Autobuild
          path: release/

      - name: Starte Build-Test mit gclibc
        run: |
          cd SOURCE
          make build-test-glibc
          
