name: Auto-Build & Deploy

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/autobuild/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Installiere Build-Tools
        run: sudo apt update && sudo apt install -y build-essential flex bison gsoap binutils make automake autoconf autoconf-archive

      - name: Download der Quellen
        run: |
          cd SOURCE
          make mrproper-full download

      - name: Starte Build-Test mit uclibc
        run: |
          cd SOURCE
          make build-test-uclibc

      - name: Release erstellen
        run: |
          cd SOURCE
          make release
          mkdir -p ../docs/autobuild
          cp LSCamoflash-*-uclibc.tar.gz ../docs/autobuild/LSCamoflash-Autobuild.tar.gz

      - name: Update erstellen
        run: |
          cd SOURCE
          make update
          mkdir -p ../docs/autobuild
          cp update-*-uclibc.tgz ../docs/autobuild/update-autobuild.tgz

      - name: Git Commit & Push der autobuild-Dateien
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add docs/autobuild/
          git commit -m "Auto-Build: Deploy latest build artifacts to GitHub Pages" || echo "Nothing to commit"
          git push

      - name: Starte Build-Test mit gclibc
        run: |
          cd SOURCE
          make build-test-glibc
