name: Auto-Build & Deploy

on:
  push:
    branches:
      - main  # Läuft nur, wenn auf "main" gepusht wird
  pull_request:
    branches:
      - main  # Optional: PRs prüfen

jobs:
  build:
    runs-on: ubuntu-latest  # Läuft auf einem Ubuntu-Runner

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Installiere Build-Tools
        run: sudo apt update && sudo apt install -y build-essential flex bison gsoap binutils make automake autoconf

      - name: Starte Build
        run: |
          cd SOURCE
          make

      - name: Erstelle Release (Optional)
        if: github.event_name == 'push'
        run: |
          tar -czvf LSCamoflash.tar.gz build/
          mkdir -p release
          mv LSCamoflash.tar.gz release/

      - name: Lade Build-Artefakte hoch (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: LSCamoflash-Build
          path: release/

      - name: Erstelle GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/LSCamoflash.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
